#!/usr/bin/env bash

set -e

for day in 1 2 3 4 6 7 8 10 11 12 13 15 16 17 18 19 20 21 22 23 24 25 26 27
do
  echo $day
  URL=`python gpxplot.py --output-format googlechart --file dan-${day}_e.gpx`
  URL=${URL/gpxplot.appspot.com/}
  URL=${URL/distance, /}
  URL=${URL/elevation, /}
  URL=${URL/600x400/740x300}
  wget -O ../dnevnik/img/dan-${day}.png "$URL"
done
exit 0
